name: floob

services:
  # Relational database
  mariadb:
    image: mariadb:11.4
    container_name: floob-mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=secret
      - MARIADB_DATABASE=floob
    ports:
      - 3306:3306
    restart: unless-stopped
    networks:
      - floob

networks:
  floob:
